from django.urls import path
from . import views
urlpatterns=[
    path('', views.index, name='index'),
    path('AdminHomePage', views.AdminHomePage, name='AdminHomePage'),
    path('employeehome', views.employeehome, name='employeehome'),
    path('hodhome', views.hodhome, name='hodhome'),
    path('LogOut',views.LogOut,name='LogOut'),
    path('login',views.login,name='login'),
    path('add_employee',views.add_employee,name='add_employee'),
    path('view_employee',views.view_employee,name='view_employee'),
    path('View_all_order',views.View_all_order,name='View_all_order'),
    path('view_category_emp',views.view_category_emp,name='view_category_emp'),
    path('Ordering_item/<int:id>',views.Ordering_item,name='Ordering_item'),
    path('Ordering_item_hod/<int:id>',views.Ordering_item_hod,name='Ordering_item_hod'),
    path('Ordering_item_guest/<int:id>',views.Ordering_item_guest,name='Ordering_item_guest'),
    path('view_category_Guest',views.view_category_Guest,name='view_category_Guest'),
    path('view_category_Hod',views.view_category_Hod,name='view_category_Hod'),
    path('breakfast', views.breakfast, name='breakfast'),
    path('lunch', views.lunch, name='lunch'),
    path('dinner', views.dinner, name='dinner'),
    path('breakfast_hod', views.breakfast_hod, name='breakfast_hod'),
    path('lunch_hod', views.lunch_hod, name='lunch_hod'),
    path('dinner_hod', views.dinner_hod, name='dinner_hod'),
    path('breakfast_guest', views.breakfast_guest, name='breakfast_guest'),
    path('lunch_guest', views.lunch_guest, name='lunch_guest'),
    path('dinner_guest', views.dinner_guest, name='dinner_guest'),
    path('View_chart/',views.view_chart,name='View_chart'),
    path('api_Breakfast', views.api_Breakfast, name='api_Breakfast'), 
    path('api_Lunch', views.api_Lunch, name='api_Lunch'), 
    path('api_Dinner', views.api_Dinner, name='api_Dinner'), 
    path('Employeecreate', views.Employeecreate, name='Employeecreate'),
    path('Showall_Employee', views.Showall_Employee, name='Showall_Employee'),
    path('signup', views.signup, name='signup'),  
    path('Showall_Orders', views.Showall_Orders, name='Showall_Orders'), 
]
